const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches,clamp=v=>Math.max(0,Math.min(1,v));const orb=document.querySelector('.hero-orb'),portal=document.querySelector('.portal'),circle=document.querySelector('.portal-circle'),seq=document.querySelector('.sequence'),words=[...document.querySelectorAll('.sequence-word')];let busy=false;function update(){const y=scrollY,max=document.documentElement.scrollHeight-innerHeight;document.querySelector('.progress').style.transform=`scaleX(${max?y/max:0})`;if(!reduce){orb.style.transform=`translate(${Math.min(y*.08,90)}px,${Math.min(y*.18,180)}px) rotate(${Math.min(y*.025,22)}deg) scale(${1+clamp(y/innerHeight)*.25})`;const p=portal.getBoundingClientRect(),t=clamp(-p.top/Math.max(1,p.height-innerHeight));circle.style.transform=`scale(${1+t*9}) rotate(${t*45}deg)`;document.querySelector('.portal-copy').style.opacity=String(clamp(1-t*.85));const s=seq.getBoundingClientRect(),phase=clamp(-s.top/Math.max(1,s.height-innerHeight))*3;words.forEach((el,i)=>{const d=i+.5-phase,alpha=clamp(1.3-Math.abs(d)*1.5);el.style.opacity=alpha;el.style.transform=`translateY(${d*110}%) rotate(${d*8}deg) scale(${.85+alpha*.15})`});document.querySelector('.sequence-num').textContent=`${String(Math.min(3,Math.floor(phase)+1)).padStart(2,'0')} / 03`}busy=false}addEventListener('scroll',()=>{if(!busy){busy=true;requestAnimationFrame(update)}},{passive:true});addEventListener('resize',update);update();const obs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('on');obs.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.manifesto h2,.manifesto-center p,.contact-section h2,.contact-pill').forEach(el=>{el.classList.add('reveal');if(reduce)el.classList.add('on');else obs.observe(el)});if(!reduce&&matchMedia('(pointer:fine)').matches){const c=document.querySelector('.cursor');addEventListener('pointermove',e=>{c.classList.add('on');c.style.left=e.clientX+'px';c.style.top=e.clientY+'px'},{passive:true})}const canvas=document.querySelector('#stars');if(!reduce&&canvas.getContext){const ctx=canvas.getContext('2d');let active=false,running=false,points=[],w,h;function size(){w=canvas.clientWidth;h=canvas.clientHeight;const d=Math.min(devicePixelRatio||1,2);canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0);points=Array.from({length:Math.min(140,Math.round(w/10))},()=>({x:Math.random()*w,y:Math.random()*h,r:Math.random()*1.2+.3,s:Math.random()*.5+.1}))}size();addEventListener('resize',size);new IntersectionObserver(([e])=>{active=e.isIntersecting;if(active&&!running){running=true;requestAnimationFrame(draw)}}).observe(canvas);function draw(){if(!active){running=false;return}ctx.clearRect(0,0,w,h);for(const p of points){p.y-=p.s;if(p.y<0)p.y=h;ctx.fillStyle='#b2a7e2';ctx.globalAlpha=.25+p.r*.35;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,7);ctx.fill()}requestAnimationFrame(draw)}}

const menuToggle=document.querySelector('.menu-toggle'),mobileNav=document.querySelector('#mobile-nav');
function closeMenu(){mobileNav.hidden=true;menuToggle.setAttribute('aria-expanded','false');menuToggle.setAttribute('aria-label','Abrir menú')}
menuToggle.addEventListener('click',()=>{const opening=mobileNav.hidden;mobileNav.hidden=!opening;menuToggle.setAttribute('aria-expanded',String(opening));menuToggle.setAttribute('aria-label',opening?'Cerrar menú':'Abrir menú')});
mobileNav.querySelectorAll('a').forEach(link=>link.addEventListener('click',closeMenu));
addEventListener('keydown',event=>{if(event.key==='Escape'&&!mobileNav.hidden){closeMenu();menuToggle.focus()}});
addEventListener('resize',()=>{if(innerWidth>700)closeMenu()});

menuToggle.addEventListener("click",()=>document.body.classList.toggle("overlay-open",!mobileNav.hidden));mobileNav.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>document.body.classList.remove("overlay-open")));addEventListener("keydown",e=>{if(e.key==="Escape")document.body.classList.remove("overlay-open")});addEventListener("resize",()=>document.body.classList.remove("overlay-open"));
